services:
  db:
    image: postgres:18
    container_name: plog-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev_db
    volumes:
      - plog-postgres-data:/var/lib/postgresql/data

volumes:
  plog-postgres-data:
